#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

INSTALL_DIR="/opt/postfix-admin"
APP_USER="postfixadmin"
APP_GROUP="postfixadmin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WHEEL_FILE="$SCRIPT_DIR/Flask_Login-0.6.3-py3-none-any.whl"
REQUIREMENTS_FILE="$REPO_ROOT/requirements.txt"
SENDER_MAP="/etc/postfix/sender_transport"
SASL_PASSWD="/etc/postfix/sender_sasl_passwd"
MAIN_CF="/etc/postfix/main.cf"
TLS_CERT="/etc/nginx/ssl/postfix-admin.crt"
TLS_KEY="/etc/nginx/ssl/postfix-admin.key"
SERVICE_FILE="/etc/systemd/system/postfix-admin.service"
VENV_DIR="$INSTALL_DIR/venv"
VENV_PIP="$VENV_DIR/bin/pip"
VENV_GUNICORN="$VENV_DIR/bin/gunicorn"
VENV_FLASK="$VENV_DIR/bin/flask"

detect_postfix_routing() {
    ROUTING_MODE="unknown"
    ROUTING_MAP=""
    RELAYHOST_MAPS=""
    TRANSPORT_MAPS=""
    SASL_AUTH=""
    SASL_MAPS=""

    if ! command -v postconf >/dev/null 2>&1; then
        return 1
    fi

    RELAYHOST_MAPS=$(postconf -h sender_dependent_relayhost_maps 2>/dev/null || true)
    TRANSPORT_MAPS=$(postconf -h sender_dependent_default_transport_maps 2>/dev/null || true)
    SASL_AUTH=$(postconf -h smtp_sender_dependent_authentication 2>/dev/null || true)
    SASL_MAPS=$(postconf -h smtp_sasl_password_maps 2>/dev/null || true)

    if [ -n "$TRANSPORT_MAPS" ]; then
        ROUTING_MODE="transport"
        ROUTING_MAP="${TRANSPORT_MAPS#hash:}"
        ROUTING_MAP="${ROUTING_MAP#texthash:}"
    elif [ -n "$RELAYHOST_MAPS" ]; then
        ROUTING_MODE="relayhost"
        ROUTING_MAP="${RELAYHOST_MAPS#hash:}"
        ROUTING_MAP="${ROUTING_MAP#texthash:}"
    else
        ROUTING_MODE="relayhost"
        ROUTING_MAP="$SENDER_MAP"
    fi
    return 0
}

ensure_sender_map_file() {
    local file="$1"
    local mode="$2"
    if [ -f "$file" ]; then
        echo -e "${GREEN}Found existing map: ${file}${NC}"
        return 0
    fi
    echo -e "${YELLOW}Creating empty map: ${file}${NC}"
    cat > "$file" << EOF
# Postfix sender-dependent routing map
# Mode: ${mode}
# Managed via web interface

EOF
    chmod 644 "$file"
    postmap "$file"
}

ensure_json_file() {
    local file="$1"
    local default_content="$2"
    local owner="$3"
    local mode="$4"
    if [ -f "$file" ]; then
        echo -e "${GREEN}Preserving existing file: ${file}${NC}"
    else
        echo "$default_content" > "$file"
    fi
    chown "$owner" "$file"
    chmod "$mode" "$file"
}

ensure_nginx_allow_conf() {
    local file="$1"
    local owner="$2"
    if [ -f "$file" ]; then
        echo -e "${GREEN}Preserving existing nginx allow config: ${file}${NC}"
    else
        cat > "$file" << 'EOF'
# Generated by Postfix Admin — do not edit manually
allow all;
EOF
    fi
    chown "$owner" "$file"
    chmod 644 "$file"
}

get_existing_secret_key() {
    if [ -f "$SERVICE_FILE" ]; then
        sed -n 's/^Environment="SECRET_KEY=\(.*\)"$/\1/p' "$SERVICE_FILE" | head -n 1
    fi
}

setup_python_env() {
    echo -e "\n${GREEN}Creating Python virtual environment...${NC}"
    python3 -m venv "$VENV_DIR"
    "$VENV_PIP" install --upgrade pip
    if [ -f "$WHEEL_FILE" ]; then
        "$VENV_PIP" install "$WHEEL_FILE"
    fi
    if [ ! -f "$INSTALL_DIR/requirements.txt" ]; then
        echo -e "${RED}requirements.txt not found in $INSTALL_DIR${NC}"
        exit 1
    fi
    "$VENV_PIP" install -r "$INSTALL_DIR/requirements.txt"
}

print_routing_summary() {
    echo -e "\n${BLUE}=========================================${NC}"
    echo -e "${BLUE}Postfix sender routing (existing config)${NC}"
    echo -e "${BLUE}=========================================${NC}"

    if ! detect_postfix_routing; then
        echo -e "${YELLOW}postconf not found — Postfix routing was not inspected.${NC}"
        return
    fi

    echo -e "Detected mode: ${YELLOW}${ROUTING_MODE}${NC}"
    echo -e "Map file:      ${YELLOW}${ROUTING_MAP}${NC}"
    [ -n "$RELAYHOST_MAPS" ] && echo -e "relayhost maps: ${RELAYHOST_MAPS}"
    [ -n "$TRANSPORT_MAPS" ] && echo -e "transport maps: ${TRANSPORT_MAPS}"
    [ -n "$SASL_AUTH" ] && echo -e "sender SASL:    ${SASL_AUTH}"
    [ -n "$SASL_MAPS" ] && echo -e "SASL maps:      ${SASL_MAPS}"

    if [ -z "$RELAYHOST_MAPS" ] && [ -z "$TRANSPORT_MAPS" ]; then
        echo -e "${YELLOW}No sender routing parameter found in main.cf.${NC}"
        echo -e "Suggested Mode B (relayhost):"
        echo -e "  sender_dependent_relayhost_maps = hash:${SENDER_MAP}"
        echo -e "Configure via web panel → Configuration, then: postfix reload"
    fi

    if [ "$ROUTING_MODE" = "relayhost" ] && [ "$SASL_AUTH" != "yes" ]; then
        echo -e "${YELLOW}For per-sender SASL in relayhost mode also set:${NC}"
        echo -e "  smtp_sender_dependent_authentication = yes"
        echo -e "  smtp_sasl_password_maps = hash:${SASL_PASSWD}"
    fi
}

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Postfix Admin Installation${NC}"
echo -e "${BLUE}=========================================${NC}"

echo -e "\n${GREEN}Installing system dependencies...${NC}"
dnf install -y epel-release
dnf install -y python3 python3-pip python3-flask python3-gunicorn postfix nginx openssl nmap-ncat curl

if ! systemctl is-active --quiet postfix 2>/dev/null; then
    echo -e "${YELLOW}Warning: Postfix service is not running. Start it after configuration.${NC}"
fi

echo -e "\n${GREEN}Creating application user...${NC}"
useradd -r -U -s /sbin/nologin -d "$INSTALL_DIR" "$APP_USER" 2>/dev/null || true

echo -e "\n${GREEN}Setting up directory structure...${NC}"
if [ ! -f "$REPO_ROOT/app.py" ]; then
    echo -e "${RED}Source file not found: $REPO_ROOT/app.py${NC}"
    echo -e "${YELLOW}Run deploy/install.sh from a real repository checkout.${NC}"
    exit 1
fi
if [ ! -d "$REPO_ROOT/templates" ] || [ ! -d "$REPO_ROOT/static" ] || [ ! -d "$REPO_ROOT/deploy" ]; then
    echo -e "${RED}Repository layout is incomplete under $REPO_ROOT${NC}"
    exit 1
fi
if [ ! -f "$REQUIREMENTS_FILE" ]; then
    echo -e "${RED}Source file not found: $REQUIREMENTS_FILE${NC}"
    exit 1
fi
mkdir -p "$INSTALL_DIR"/{templates,static,deploy}
cp "$REPO_ROOT/app.py" "$INSTALL_DIR/"
cp "$REQUIREMENTS_FILE" "$INSTALL_DIR/"
cp -r "$REPO_ROOT/templates"/. "$INSTALL_DIR/templates/"
cp -r "$REPO_ROOT/static"/. "$INSTALL_DIR/static/"
cp "$REPO_ROOT/deploy/nginx-https.conf" "$INSTALL_DIR/deploy/"
cp "$REPO_ROOT/deploy/postfix-admin.service" "$INSTALL_DIR/deploy/"
cp "$REPO_ROOT/deploy/install.sh" "$INSTALL_DIR/deploy/"
cp "$REPO_ROOT/deploy/uninstall.sh" "$INSTALL_DIR/deploy/"
cp "$REPO_ROOT/deploy/update.sh" "$INSTALL_DIR/deploy/" 2>/dev/null || true
setup_python_env

echo -e "\n${GREEN}Checking Postfix sender routing files...${NC}"
detect_postfix_routing || true
MAP_TO_ENSURE="${ROUTING_MAP:-$SENDER_MAP}"
ensure_sender_map_file "$MAP_TO_ENSURE" "${ROUTING_MODE:-relayhost}"
ensure_sender_map_file "$SASL_PASSWD" "sasl"
if [ -f "$SASL_PASSWD" ]; then
    chmod 600 "$SASL_PASSWD"
fi
print_routing_summary

echo -e "\n${GREEN}Generating self-signed SSL certificate...${NC}"
mkdir -p /etc/nginx/ssl
if [ -f "$TLS_CERT" ] && [ -f "$TLS_KEY" ]; then
    echo -e "${GREEN}Existing TLS certificate/key found, preserving them.${NC}"
elif [ -f "$TLS_CERT" ] || [ -f "$TLS_KEY" ]; then
    echo -e "${RED}Only one TLS file exists. Resolve the mismatch first:${NC}"
    echo -e "  cert: $TLS_CERT"
    echo -e "  key:  $TLS_KEY"
    exit 1
else
    openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
        -keyout "$TLS_KEY" \
        -out "$TLS_CERT" \
        -subj "/C=RU/ST=Moscow/L=Moscow/O=InterROS/CN=$(hostname -I | awk '{print $1}')"
fi

chmod 600 "$TLS_KEY"
chmod 644 "$TLS_CERT"

echo -e "\n${GREEN}Generating nginx IP allow config...${NC}"
ensure_nginx_allow_conf "$INSTALL_DIR/nginx-allow.conf" "$APP_USER:$APP_GROUP"

echo -e "\n${GREEN}Configuring Nginx...${NC}"
rm -f /etc/nginx/conf.d/default.conf
cp "$INSTALL_DIR/deploy/nginx-https.conf" /etc/nginx/conf.d/postfix-admin.conf

if nginx -t 2>&1; then
    echo -e "${GREEN}Nginx configuration is OK.${NC}"
else
    echo -e "${RED}Nginx configuration test failed! Aborting.${NC}"
    exit 1
fi

echo -e "\n${GREEN}Creating systemd service with Gunicorn (root)...${NC}"
SECRET_KEY="$(get_existing_secret_key)"
if [ -n "$SECRET_KEY" ]; then
    echo -e "${GREEN}Reusing existing SECRET_KEY from installed service.${NC}"
else
    SECRET_KEY="$(openssl rand -hex 32)"
fi
cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Postfix Admin Web Interface
After=network.target postfix.service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=$INSTALL_DIR
Environment="SECRET_KEY=$SECRET_KEY"
Environment="USERS_FILE=$INSTALL_DIR/users.json"
ExecStart=$VENV_GUNICORN -w 4 -b 127.0.0.1:8000 app:app
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable postfix-admin

echo -e "\n${GREEN}Setting permissions...${NC}"
chown -R "$APP_USER:$APP_GROUP" "$INSTALL_DIR"

ensure_json_file "$INSTALL_DIR/users.json" "{}" "$APP_USER:$APP_GROUP" 600
ensure_json_file "$INSTALL_DIR/ip_whitelist.json" "[]" "$APP_USER:$APP_GROUP" 640

echo -e "\n${GREEN}Configuring log file access...${NC}"
if getent group adm > /dev/null; then
    usermod -a -G adm "$APP_USER"
fi
if [ -f /var/log/maillog ]; then
    chmod 644 /var/log/maillog
fi

echo -e "\n${GREEN}Firewall...${NC}"
firewall-cmd --permanent --add-service=http --add-service=https 2>/dev/null || true
firewall-cmd --reload 2>/dev/null || true

# Запуск сервисов
echo -e "\n${GREEN}Starting postfix-admin with Gunicorn...${NC}"
systemctl start postfix-admin
sleep 2
if systemctl is-active --quiet postfix-admin; then
    echo -e "${GREEN}postfix-admin is running.${NC}"
else
    echo -e "${RED}postfix-admin failed to start!${NC}"
    journalctl -u postfix-admin --no-pager -n 10
    exit 1
fi

echo -e "\n${GREEN}Starting Nginx...${NC}"
systemctl start nginx
sleep 2
if systemctl is-active --quiet nginx; then
    echo -e "${GREEN}Nginx is running.${NC}"
else
    echo -e "${RED}Nginx failed to start!${NC}"
    journalctl -u nginx --no-pager -n 10
    exit 1
fi

echo -e "\n${GREEN}Checking listening ports...${NC}"
if ss -tlnp | grep ':443 ' && ss -tlnp | grep ':8000 '; then
    echo -e "${GREEN}Both ports 443 and 8000 are listening.${NC}"
else
    echo -e "${RED}Port missing! Something went wrong.${NC}"
fi

# Проверка Gunicorn
sleep 2
if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/ | grep -q '302\|301'; then
    echo -e "${GREEN}Gunicorn is responding.${NC}"
else
    echo -e "${RED}Gunicorn not reachable on port 8000!${NC}"
fi

# --- Создание администратора ---
echo -e "\n${BLUE}=========================================${NC}"
echo -e "${BLUE}Creating admin user${NC}"
echo -e "${BLUE}=========================================${NC}"
read -p "Create admin user now? (y/N): " CREATE_ADMIN
if [[ "$CREATE_ADMIN" =~ ^[Yy]$ ]]; then
    cd "$INSTALL_DIR"
    export FLASK_APP=app.py
    export USERS_FILE="$INSTALL_DIR/users.json"
    "$VENV_FLASK" create-user
    chown "$APP_USER:$APP_GROUP" "$INSTALL_DIR/users.json"
    echo -e "${GREEN}Admin user created successfully!${NC}"
else
    echo -e "${YELLOW}Skipping admin creation.${NC}"
fi

echo -e "\n${GREEN}=========================================${NC}"
echo -e "${GREEN}Installation complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo -e "Access: ${YELLOW}https://$(hostname -I | awk '{print $1}')${NC}"
echo -e "Sender routing map: ${YELLOW}${ROUTING_MAP:-$SENDER_MAP}${NC}"
echo -e "Panel reads existing ${YELLOW}main.cf${NC} — map files are not overwritten if already present."